/* empty css                      */import{S as f,A as m}from"./assets/vendor-HTdmVadK.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function c(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(e){if(e.ep)return;e.ep=!0;const t=c(e);fetch(e.href,t)}})();new f(".my-swiper",{modules:[m],loop:!0,speed:6e3,allowTouchMove:!1,grabCursor:!1,slidesPerView:1.2,spaceBetween:16,autoplay:{delay:0,disableOnInteraction:!1,pauseOnMouseEnter:!1},breakpoints:{1440:{slidesPerView:2.4,spaceBetween:24}}});document.querySelectorAll(".faq-acc-el-trigger").forEach(s=>{s.addEventListener("click",()=>{const o=s.closest(".faq-acc-el"),c=o.querySelector(".faq-acc-el-descr-frame"),l=s.querySelector("svg"),e=o.classList.contains("open"),t=`
<svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M24 12L14 22L4 12" stroke="#8B8A8A" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
  <path d="M24 6L14 16L4 6" stroke="#8B8A8A" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
</svg>`,a=`
<svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M24 16L14 6L4 16" stroke="#8B8A8A" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
  <path d="M24 22L14 12L4 22" stroke="#8B8A8A" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
</svg>`;e?(o.classList.remove("open"),c.style.maxHeight="0",l.outerHTML=t):(o.classList.add("open"),c.style.maxHeight=c.scrollHeight+"px",l.outerHTML=a)})});document.addEventListener("DOMContentLoaded",()=>{const s=document.querySelector(".menu-button"),o=s.querySelector(".icon"),c=document.querySelector(".modal"),l=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const a=`
<svg width="26" height="18" viewBox="0 0 26 18" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M25 17L1 17" stroke="white" stroke-width="2" stroke-linecap="round" />
  <path d="M25 9L1 9" stroke="white" stroke-width="2" stroke-linecap="round" />
  <path d="M25 1L1 1" stroke="white" stroke-width="2" stroke-linecap="round" />
</svg>
    `,n=`
<svg width="41" height="41" viewBox="0 0 41 41" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M34.1663 34.1667L6.83301 6.83333M34.1663 6.83333L6.83301 34.1667" stroke="#fff" stroke-width="2" stroke-linecap="round" />
</svg>
    `;s.addEventListener("click",()=>{t=!t,o.innerHTML=t?n:a,t?r():i()}),l.forEach(u=>u.addEventListener("click",()=>{i(),o.innerHTML=a,t=!1})),window.addEventListener("scroll",d);function r(){c.style.display="block"}function i(){c.style.display="none"}function d(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function s(){const n=document.getElementById("site-header");return n?n.offsetHeight:0}function o(n){const r=document.getElementById(n);if(!r)return;const i=s(),d=r.getBoundingClientRect().top+window.pageYOffset-i;window.scrollTo({top:d,behavior:"smooth"})}document.querySelectorAll(".navigation-item a").forEach(n=>{n.addEventListener("click",function(r){const i=this.getAttribute("href");if(!i)return;const[d,u]=i.split("#");if(!u)return;const p=window.location.pathname.split("/").pop();!(d===""||d==="./"||d===p||d==="./"+p)||!document.getElementById(u)||(r.preventDefault(),o(u),t(u))})});const l=document.querySelectorAll("section[id]"),e=document.querySelectorAll(".navigation-item");function t(n){e.forEach(i=>i.classList.remove("active"));const r=document.querySelector(`.navigation-item a[href*="#${n}"]`);r&&r.closest(".navigation-item").classList.add("active")}function a(){const n=window.pageYOffset+s()+100;l.forEach(r=>{const i=r.offsetTop,d=i+r.offsetHeight;n>=i&&n<d&&t(r.id)})}if(window.addEventListener("scroll",a),window.location.hash){const n=window.location.hash.substring(1);setTimeout(()=>{o(n),t(n)},300)}});document.addEventListener("DOMContentLoaded",function(){const s=document.getElementById("cookie-popup"),o=document.getElementById("accept-cookies"),c=document.getElementById("decline-cookies");localStorage.getItem("cookiesAccepted")||(s.style.display="block"),o.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","yes"),s.style.display="none"}),c.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","no"),s.style.display="none"})});
//# sourceMappingURL=index.js.map
